name: Deploy
on:
  push:
    branches: -deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: npm run lint

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: npx typecheck --if-present 

  vitest:
    name: vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: vitest
        run: npm run test

  deploy:
    name: Deploy 
    if: ${{ github.ref == 'refs/heads/dev' }}
    needs: [lint, typecheck, vitest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

