name: Deploy

on:
  push:
    branches: -test_deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm exec lint // insert lint command here

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: pnpm exec typecheck --if-present // insert typecheck command here

  vitest:
    name: vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: vitest
        run: pnpm exec test -- --coverage // insert vitest command here

  deploy:
    name: Deploy to EC2
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install deps
        run: pnpm install

      - name: Deploy to Server1
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
