name: SSH Remote Commands
on:
  push:
    branches:
      - deploy

jobs:
  # lint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         cache-dependency-path: ./package.json
  #         node-version: 18

  #     - name: Install deps
  #       run: npm install

  #     - name: Lint
  #       run: npm run lint

  # typecheck:
  #   name: Typescript
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         cache-dependency-path: ./package.json
  #         node-version: 18

  # vitest:
  #   name: vitest
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         cache-dependency-path: ./package.json
  #         node-version: 18

  #     - name: Install deps
  #       run: npm install

  #     - name: vitest
  #       run: npm run test

  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/deploy' }}
    needs: []
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 18

      - uses: actions/checkout@v1
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/osport/projet-o-sport-back
            git fetch
            git checkout deploy
            git reset --hard origin/deploy
            git pull origin deploy
            npm run build
